//
//  Array.swift
//  iOSCertificationTest
//
//  Created by Michael Sidoruk on 15/05/2019.
//  Copyright © 2019 Michael Sidoruk. All rights reserved.
//

struct Helpers {
    
static var questions: [Question] = [
    Question(text: "What output will be produced by the code above?",
             answer: [Answer(text: "\"Square root of 25.0 is 5.0\"", type: true),
                      Answer(text: "\"Square root of 25 is 5\"", type: false),
                      Answer(text: "\"Square root of 5 is 25\"", type: false),
                      Answer(text: "The code won't be compilled", type: false),],
             image: "1"),
    Question(text: "What output will be produced by the code above?",
             answer: [Answer(text: "\"1000\"", type: true),
                      Answer(text: "\"1_000\"", type: false),
                      Answer(text: "\"_1000_\"", type: false),
                      Answer(text: "\"1000.0\"", type: false),],
             image: "2"),
    Question(text: "When the code is executed, what is the value of someString?",
             answer: [Answer(text: "\"Hello\"", type: true),
                      Answer(text: "\"0\"", type: false),
                      Answer(text: "The code won't be executed", type: false),
                      Answer(text: "\"0 Hello\"", type: false),],
             image: "3"),
    Question(text: "What output will be produced by the code above?",
             answer: [Answer(text: "The code won't be executed", type: true),
                      Answer(text: "\"Abc\", \"Dfe\"", type: false),
                      Answer(text: "\"ABC\", \"DFE\"", type: false),
                      Answer(text: "\"abc\", \"dfe\"", type: false),],
             image: "4"),
    Question(text: "What data type does the \"number\" constant have?",
             answer: [Answer(text: "Double", type: true),
                      Answer(text: "Float", type: false),
                      Answer(text: "CGFloat", type: false),
                      Answer(text: "The code won't be compilled", type: false),],
             image: "5"),
    Question(text: "What output will be produced by the code above?",
             answer: [Answer(text: "\"The number is 1\"", type: true),
                      Answer(text: "\"The number is 2\"", type: false),
                      Answer(text: "\"The number is 3\"", type: false),
                      Answer(text: "The code won't be compilled", type: false),],
             image: "6"),
    Question(text: "What output will be produced by the code above?",
             answer: [Answer(text: "The code won't be compilled", type: true),
                      Answer(text: "Nothing", type: false),
                      Answer(text: "\"Woof, Woof!\"", type: false),
                      Answer(text: "\"What does the husky say?\"", type: false),],
             image: "9"),
    Question(text: "How many values will the array contain?",
             answer: [Answer(text: "The code won't be compilled", type: true),
                      Answer(text: "0", type: false),
                      Answer(text: "3", type: false),
                      Answer(text: "1", type: false),],
             image: "7"),
    Question(text: "What will the third constant contain?",
             answer: [Answer(text: "\"a\", \"b\", \"c\", \"d\"", type: true),
                      Answer(text: "The code won't be compilled", type: false),
                      Answer(text: "\"a\", \"b\"", type: false),
                      Answer(text: "\"c\", \"d\"", type: false),],
             image: "8"),
    Question(text: "What output will be produced the code above",
             answer: [Answer(text: "\"128\"", type: true),
                      Answer(text: "\"64\"", type: false),
                      Answer(text: "\"127\"", type: false),
                      Answer(text: "\"2\"", type: false),],
             image: "10"),
    Question(text: "What output will be produced the code above, if the function throw \"Declined\"?",
             answer: [Answer(text: "\"Declined\"", type: true),
                      Answer(text: "\"error\"", type: false),
                      Answer(text: "The code won't be compilled", type: false),
                      Answer(text: "Nothing", type: false),],
             image: "11"),
    Question(text: "What value will the constant have?",
             answer: [Answer(text: "0", type: true),
                      Answer(text: "-2147483648", type: false),
                      Answer(text: "-65536", type: false),
                      Answer(text: "-256", type: false),],
             image: "12"),
    Question(text: "What output will be produced the code above?",
             answer: [Answer(text: "The code won't be compilled", type: true),
                      Answer(text: "\"Tesla\"", type: false),
                      Answer(text: "\"2\"", type: false),
                      Answer(text: "Nothing", type: false),],
             image: "13"),
    Question(text: "What output will be produced the code above?",
             answer: [Answer(text: "\"Moscow\", \"Minsk\"", type: true),
                      Answer(text: "\"Rome\", \"Minsk\"", type: false),
                      Answer(text: "\"Moscow\", \"Tampa\"", type: false),
                      Answer(text: "\"Rome\", \"Tampa\"", type: false),],
             image: "14"),
    Question(text: "What output will be producted the code above?",
             answer: [Answer(text: "\"iPhone Xs\"", type: true),
                      Answer(text: "\"Samsung 10\"", type: false),
                      Answer(text: "The code won't be compilled", type: false),
                      Answer(text: "Nothing", type: false),],
             image: "15"),
    Question(text: "What will be the value of the \"number2\" constant?",
             answer: [Answer(text: "22 as String", type: true),
                      Answer(text: "4 as Int", type: false),
                      Answer(text: "The code won't be compilled", type: false),
                      Answer(text: "4 as String", type: false),],
             image: "16"),
    Question(text: "What output will be producted the code above?",
             answer: [Answer(text: "\"New York\"", type: true),
                      Answer(text: "\"Lodon\"", type: false),
                      Answer(text: "The code won't be compilled", type: false),
                      Answer(text: "Nothing", type: false),],
             image: "17"),
    Question(text: "What output will be producted the code above?",
             answer: [Answer(text: "The code won't be compilled", type: true),
                      Answer(text: "\"5\"", type: false),
                      Answer(text: "\"5.0\"", type: false),
                      Answer(text: "Nothing", type: false),],
             image: "18"),
    Question(text: "What output will be produced by the code above?",
             answer: [Answer(text: "\"I use skate\"", type: true),
                      Answer(text: "\"I use bicycle\", \"I use skate\"", type: false),
                      Answer(text: "The code won't be compilled", type: false),
                      Answer(text: "Nothing", type: false),],
             image: "19"),
    Question(text: "How many bits are used to store an \"Int\"?",/////////////don't have any image
        answer: [Answer(text: "It depends on a device", type: true),
                 Answer(text: "64", type: false),
                 Answer(text: "32", type: false),
                 Answer(text: "16", type: false),],
        image: "default"),
    Question(text: "What is the name of this interface element?",
             answer: [Answer(text: "Custom segue", type: true),
                      Answer(text: "Popover segue", type: false),
                      Answer(text: "Navigation segue", type: false),
                      Answer(text: "Modally segue", type: false),],
             image: "20"),
    Question(text: "What's the name of this interface element?",
             answer: [Answer(text: "Popover segue", type: true),
                      Answer(text: "Custom segue", type: false),
                      Answer(text: "Show detail segue", type: false),
                      Answer(text: "Show segue", type: false),],
             image: "21"),
    Question(text: "What's the name of this interface element?",
             answer: [Answer(text: "Show detail segue", type: true),
                      Answer(text: "Custom segue", type: false),
                      Answer(text: "Modally segue", type: false),
                      Answer(text: "Show segue", type: false),],
             image: "22"),
    Question(text: "What's the name of this interface element?",
             answer: [Answer(text: "Modally segue", type: true),
                      Answer(text: "Show detail segue", type: false),
                      Answer(text: "Custom segue", type: false),
                      Answer(text: "Show segue", type: false),],
             image: "24"),
    Question(text: "What's the name of this interface element?",
             answer: [Answer(text: "Library", type: true),
                      Answer(text: "Assisten editor", type: false),
                      Answer(text: "Custom UI", type: false),
                      Answer(text: "Views", type: false),],
             image: "25"),
    Question(text: "What's the name of this interface element?",
             answer: [Answer(text: "Standart editor", type: true),
                      Answer(text: "Assisten editor", type: false),
                      Answer(text: "Custom editor", type: false),
                      Answer(text: "Version editor", type: false),],
             image: "26"),
    Question(text: "What's the name of this interface element?",
             answer: [Answer(text: "Assisten editor", type: true),
                      Answer(text: "Custom editor", type: false),
                      Answer(text: "Version editor", type: false),
                      Answer(text: "Standart editor", type: false),],
             image: "27"),
    Question(text: "What's the name of this interface element?",
             answer: [Answer(text: "Version editor", type: true),
                      Answer(text: "Assisten editor", type: false),
                      Answer(text: "Custom editor", type: false),
                      Answer(text: "Standart editor", type: false),],
             image: "28"),
    Question(text: "What's the name of this interface element?",
             answer: [Answer(text: "Show navigator", type: true),
                      Answer(text: "Show storyboard", type: false),
                      Answer(text: "Show view", type: false),
                      Answer(text: "Show assisten editor", type: false),],
             image: "29"),
    Question(text: "What's the name of this interface element?",
             answer: [Answer(text: "Show debug area", type: true),
                      Answer(text: "Show navigator", type: false),
                      Answer(text: "Show inspectors", type: false),
                      Answer(text: "Show storyboard", type: false),],
             image: "30"),
    Question(text: "What's the name of this interface element?",
             answer: [Answer(text: "Show inspectors", type: true),
                      Answer(text: "Show navigator", type: false),
                      Answer(text: "Show debug area", type: false),
                      Answer(text: "Show storyboard", type: false),],
             image: "31"),
    Question(text: "What's the name of this interface element?",
             answer: [Answer(text: "File inspector", type: true),
                      Answer(text: "Help inspector", type: false),
                      Answer(text: "Size inspector", type: false),
                      Answer(text: "Identity inspector", type: false),],
             image: "32"),
    Question(text: "What's the name of this interface element?",
             answer: [Answer(text: "Help inspector", type: true),
                      Answer(text: "Size inspector", type: false),
                      Answer(text: "Identity inspector", type: false),
                      Answer(text: "Connections inspector", type: false),],
             image: "33"),
    Question(text: "What's the name of this interface element?",
             answer: [Answer(text: "Identity inspector", type: true),
                      Answer(text: "Help inspector", type: false),
                      Answer(text: "Connections inspector", type: false),
                      Answer(text: "File inspector", type: false),],
             image: "34"),
    Question(text: "What's the name of this interface element?",
             answer: [Answer(text: "Attributes inspector", type: true),
                      Answer(text: "Help inspector", type: false),
                      Answer(text: "Identity inspector", type: false),
                      Answer(text: "File inspector", type: false),],
             image: "35"),
    Question(text: "What's the name of this interface element?",
             answer: [Answer(text: "Size inspector", type: true),
                      Answer(text: "Attributes inspector", type: false),
                      Answer(text: "File inspector", type: false),
                      Answer(text: "Connections inspector", type: false),],
             image: "36"),
    Question(text: "What's the name of this interface element?",
             answer: [Answer(text: "Connections inspector", type: true),
                      Answer(text: "Identity inspector", type: false),
                      Answer(text: "Help inspector", type: false),
                      Answer(text: "Size inspector", type: false),],
             image: "37"),
    Question(text: "What's the name of this interface element?",
             answer: [Answer(text: "View Controller", type: true),
                      Answer(text: "File Responder", type: false),
                      Answer(text: "Exit", type: false),
                      Answer(text: "View Attributes", type: false),],
             image: "38"),
    Question(text: "What's the name of this interface element?",
             answer: [Answer(text: "File Responder", type: true),
                      Answer(text: "View Controller", type: false),
                      Answer(text: "Exit", type: false),
                      Answer(text: "View Attributes", type: false),],
             image: "39"),
    Question(text: "What's the name of this interface element?",
             answer: [Answer(text: "Exit", type: true),
                      Answer(text: "View Attributes", type: false),
                      Answer(text: "View Controller", type: false),
                      Answer(text: "File Responder", type: false),],
             image: "40"),
    Question(text: "What's the name of this interface element?",
             answer: [Answer(text: "Scheme", type: true),
                      Answer(text: "Destination", type: false),
                      Answer(text: "Schedule", type: false),
                      Answer(text: "Application", type: false),],
             image: "42"),
    Question(text: "What's the name of this interface element?",
             answer: [Answer(text: "Destination", type: true),
                      Answer(text: "Scheme", type: false),
                      Answer(text: "Schedule", type: false),
                      Answer(text: "Application", type: false),],
             image: "43"),
    Question(text: "What's the name of this interface element?",
             answer: [Answer(text: "Activity viewer", type: true),
                      Answer(text: "Status viewer", type: false),
                      Answer(text: "Activity application", type: false),
                      Answer(text: "Status application", type: false),],
             image: "44"),
    Question(text: "What's the name of this interface element?",
             answer: [Answer(text: "Outline view", type: true),
                      Answer(text: "Scheme view", type: false),
                      Answer(text: "UI view", type: false),
                      Answer(text: "Application view", type: false),],
             image: "45"),
    Question(text: "What's the name of this interface element?",
             answer: [Answer(text: "Navigator area", type: true),
                      Answer(text: "Bulding area", type: false),
                      Answer(text: "Navigation bar", type: false),
                      Answer(text: "Search area", type: false),],
             image: "46"),
    Question(text: "What's the name of this interface element?",
             answer: [Answer(text: "Storyboard device", type: true),
                      Answer(text: "Building device", type: false),
                      Answer(text: "View device", type: false),
                      Answer(text: "Orientation device", type: false),],
             image: "47"),
    Question(text: "What's the name of this interface element?",
             answer: [Answer(text: "Update frames", type: true),
                      Answer(text: "Embeded in", type: false),
                      Answer(text: "Align", type: false),
                      Answer(text: "Resolve issues", type: false),],
             image: "48"),
    Question(text: "What's the name of this interface element?",
             answer: [Answer(text: "Embeded in", type: true),
                      Answer(text: "Align", type: false),
                      Answer(text: "Update frames", type: false),
                      Answer(text: "Add new constraints", type: false),],
             image: "49"),
    Question(text: "What's the name of this interface element?",
             answer: [Answer(text: "Align", type: true),
                      Answer(text: "Embeded in", type: false),
                      Answer(text: "Update frames", type: false),
                      Answer(text: "Resolve issues", type: false),],
             image: "50"),
    Question(text: "What's the name of this interface element?",
             answer: [Answer(text: "Add new constraints", type: true),
                      Answer(text: "Resolve issues", type: false),
                      Answer(text: "Update frames", type: false),
                      Answer(text: "Align", type: false),],
             image: "51"),
    Question(text: "What's the name of this interface element?",
             answer: [Answer(text: "Resolve issues", type: true),
                      Answer(text: "Align", type: false),
                      Answer(text: "Update frames", type: false),
                      Answer(text: "Add new constraints", type: false),],
             image: "52"),
    Question(text: "What's the name of this interface element?",
             answer: [Answer(text: "Run button", type: true),
                      Answer(text: "Beggin button", type: false),
                      Answer(text: "Forward button", type: false),
                      Answer(text: "Start button", type: false),],
             image: "55"),
    Question(text: "What's the name of this interface element?",
             answer: [Answer(text: "Stop button", type: true),
                      Answer(text: "Pause button", type: false),
                      Answer(text: "Close button", type: false),
                      Answer(text: "Cancel button", type: false),],
             image: "56"),
    Question(text: "What's the name of this interface element?",
             answer: [Answer(text: "Project navigator", type: true),
                      Answer(text: "Source control navigator", type: false),
                      Answer(text: "Test navigator", type: false),
                      Answer(text: "Symbol navigator", type: false),],
             image: "57"),
    Question(text: "What's the name of this interface element?",
             answer: [Answer(text: "Source control navigator", type: true),
                      Answer(text: "Project navigator", type: false),
                      Answer(text: "Test navigator", type: false),
                      Answer(text: "Breakpoint navigator", type: false),],
             image: "58"),
    Question(text: "What's the name of this interface element?",
             answer: [Answer(text: "Symbol navigator", type: true),
                      Answer(text: "Source control navigator", type: false),
                      Answer(text: "Issue navigator", type: false),
                      Answer(text: "Project navigator", type: false),],
             image: "59"),
    Question(text: "What's the name of this interface element?",
             answer: [Answer(text: "Find navigator", type: true),
                      Answer(text: "Symbol navigator", type: false),
                      Answer(text: "Project navigator", type: false),
                      Answer(text: "Issue navigator", type: false),],
             image: "60"),
    Question(text: "What's the name of this interface element?",
             answer: [Answer(text: "Issue navigator", type: true),
                      Answer(text: "Find navigator", type: false),
                      Answer(text: "Test navigator", type: false),
                      Answer(text: "Symbol navigator", type: false),],
             image: "61"),
    Question(text: "What's the name of this interface element?",
             answer: [Answer(text: "Test navigator", type: true),
                      Answer(text: "Issue navigator", type: false),
                      Answer(text: "Find navigator", type: false),
                      Answer(text: "Project navigator", type: false),],
             image: "62"),
    Question(text: "What's the name of this interface element?",
             answer: [Answer(text: "Debug navigator", type: true),
                      Answer(text: "Test navigator", type: false),
                      Answer(text: "Issue navigator", type: false),
                      Answer(text: "Symbol navigator", type: false),],
             image: "63"),
    Question(text: "What's the name of this interface element?",
             answer: [Answer(text: "Breakpoint navigator", type: true),
                      Answer(text: "Debug navigator", type: false),
                      Answer(text: "Issue navigator", type: false),
                      Answer(text: "Test navigator", type: false),],
             image: "64"),
    Question(text: "What's the name of this interface element?",
             answer: [Answer(text: "Report navigator", type: true),
                      Answer(text: "Debug navigator", type: false),
                      Answer(text: "Issue navigator", type: false),
                      Answer(text: "Find navigator", type: false),],
             image: "65"),
    Question(text: "What's the name of this interface element?",
             answer: [Answer(text: "Relationship segue", type: true),
                      Answer(text: "Show segue", type: false),
                      Answer(text: "Modally segue", type: false),
                      Answer(text: "Show detail segue", type: false),],
             image: "67"),
]

}
